[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Añadir producto al carrito

[plantuml,"Sequence diagram",png]
----
actor Cliente
participant Carrito
database MongoDB
Cliente -> Carrito: Petición de autenticación
Carrito -> Cliente: Respuesta de autenticación
Cliente -> Carrito: Añadir productos al carrito
Carrito -> MongoDB: Guardar productos del cliente
note across: Tras hacer esto, la lista del carrito tendrá guardado dicho producto
Cliente -> Carrito: Entrar al carrito
Carrito -> Cliente: Visualizar carrito
----

=== Eliminar producto del carrito.

[plantuml,"Sequence diagram",png]
----
actor Cliente
participant Carrito
Cliente -> Carrito: Entrar al carrito
Carrito -> Cliente: Mostrar carrito
Cliente -> Carrito: Eliminar el producto seleccionado
note across: Tras hacer esto, la lista del carrito dejará de mostrar dicho producto
Carrito -> Cliente: Se actualiza el carrito
----
