[[section-concepts]]
== Conceptos Transversales

=== Modelo de datos
En el modelo de datos de nuestra aplicación, al estar usando MongoDB, tenemos 3 colecciones diferentes quue almacenan los elementos con los que interactúa la
aplicación. Son las siguientes:

==== Pedidos
Son los pedidos que se realizan en la aplicación. Tiene los siguientes campos

****
* _id: Identificador único de cada pedido.
* Dirección: Dirección del cliente que realizar el pedido, que incluye los campos Calle, Localidad, Provincia, País y Código Postal.
* Lista_Productos: Lista de los productos incluídos en el pedido, mostrando su Id, su cantidad y su precio total.
* Fecha: Fecha en la que se ha realizado el Pedido.
* Numero_Pedido: Número de cada pedido.
* Id_Usuario: Identificador único del cliente que ha realizado el pedido.
* Precio_Total: Precio Total de cada pedido.
* Estado: Estado de cada pedido. Puede tomar los valores Entregado, En reparto, Pendiente, Listo para repartir y Cancelado.
****

==== Productos
Son los productos que se pueden comprar en la tienda.

****
* _id: Identificador único de cada producto.
* Nombre: Nombre del prodcuto.
* Origen: Lugar de origen del producto.
* Precio: Precio por unidad del producto.
* Descripción: Descripción del producto que muestra información sobre este.
* Foto: Enlace a un repositorio Online donde se almacenan las fotos de cada producto.
****

==== Usuarios
Son los usuarios registrados en la página, ya sean administradores o usuarios normales.

****
* _id: Identificador único de cada usuario.
* Nombre: Nombre del usuario.
* Apellidos: Apellidos del usuario.
* Email: Correo electrónico del usuario.
* Dni: Dni del usuario registrado en la página.
* Foto: Url que proporciona un avatar al usuario
* idSolid: Dirección para acceder al pod del usuario. (Por ejemplo: usuario.solidcommunity.net)
* Contraseña: Contraseña de acceso del usuario, que se guarda cifrada en la base de datos.
****

=== Modelo de dominio

[plantuml, "DomainModel", png]
----
object Usuario{
    _id : String
    nombre : String
    apellidos : String
    dni : String
    foto : String
    idSolid : boolean
    email : String
    contraseña : String
}

object Producto{
    _id : String
    nombre : String
    origen : String
    descripcion : String
    precio : double
    cantidad : int
    foto : String
}

object Pedido{
    id_producto : String
    cantidad : int
    precio : double
}

object Pedidos{
    _id : String
    numero_pedido : int
    id_usuario : String
    direccion : Direccion
    Lista_Productos: Array[Pedido]
    fecha: Date
    estado : String
    precio_total : double
}

object Tarjeta{
    numero_tarjeta : String
    fecha_caducidad : Date
    numero_seguridad : int
}

object Direccion{
    calle : String
    localidad : String
    provincia : String
    pais : String
    codigo_postal : int
}


Direccion --* Pedidos
Usuario --> Pedidos
Usuario --> Tarjeta
Tarjeta *-- Pedidos
Pedido *-- Producto
Pedido *-- Pedidos
Usuario --> Direccion


----

=== Experiencia de usuario

La interfaz de usuario deberá ser intuitiva, limpia y sencilla para facilitar al usuario el uso de la web,
y que solo se preocupe en buscar los productos que quiera y pagarlos.
La web estará, en principio, en castellano; ya que la tienda venderá productos dentro de España


=== Seguridad y consistencia

Nuestro programa está hecho de tal que garantiza la protección de los datos personales de los clientes de
nuestra tienda online. Nos aseguramos de que ningún usuario sin permisos de administrador, pueda conseguir dichos permisos
con relativa facilidad, siendo identificados los administradores por sus respectivos identificadores privados.

Esta seguridad no afecta para nada en la consistencia de la aplicación, los datos no se ven perjudicados en ningún momento.


=== Implementación

La aplicación web deberá ser persistente, guardanto tanto los datos de los productos como los de los
usuarios para que se pueda acceder a ellos en cualquier momento. Para ello será clave el uso de MondoDB.

Se contará con un control de pedidos por parte de los clientes para poder registrar sus compras. Todas estás compras quedarán
almacendas en la base de datos, tanto para el cliente que ha realizado su pedido, como para el administrador del sitio web,
el cual tendrá control absoluto de todos los pedidos que se han solicitado en la aplicación, pudiendo modificar su estado
en función de como se encuentre el pedido (procesando, enviado, recibido, etc.).


