[[section-quality-scenarios]]
== Quality Requirements

This section extends the point __1.2 Quality Goals__, describing the quality requirements of our application.
The requirements will be represented in a tree diagram, __10.1 Quality Tree__, and explained in a table, __10.2 Quality Scenarios__. 

=== Quality Tree

[plantuml,calidad,png]
----
@startmindmap

* Quality Requirements
** Privacy
** Security
** Maintainability
** Usability
** Testability
** Compatibility
** Availability
** Portability

@endmindmap
----
=== Quality Scenarios

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****
