:numbered!:
== Anexo

En este Anexo se mostrarán diferentes aspectos de la aplicación que ayudarán a entender partes que no hayan quedado explicadas por completo 
o que no corresponden a ninguno de los puntos de la documentación.

=== Modelo de datos.
En el modelo de datos de nuestra aplicación, al estar usando MongoDB, tenemos 3 colecciones diferentes quue almacenan los elementos con los que interactúa la
aplicación. Son las siguientes:

==== Pedidos.
Son los pedidos que se realizan en la aplicación. Tiene los siguientes campos

****
* _id: Identificador único de cada pedido.
* Dirección: Dirección del cliente que realizar el pedido, que incluye los campos Calle, Localidad, Provincia, País y Código Postal.
* Lista_Productos: Lista de los productos incluídos en el pedido, mostrando su Id, su cantidad y su precio total.
* Fecha: Fecha en la que se ha realizado el Pedido.
* Numero_Pedido: Número de cada pedido.
* Id_Usuario: Identificador único del cliente que ha realizado el pedido.
* Precio_Total: Precio Total de cada pedido.
* Estado: Estado de cada pedido. Puede tomar los valores Entregado, En reparto, Pendiente, Listo para repartir y Cancelado. 
****

==== Productos.
Son los productos que se pueden comprar en la tienda.

****
* _id: Identificador único de cada producto.
* Nombre: Nombre del prodcuto.
* Origen: Lugar de origen del producto.
* Precio: Precio por unidad del producto.
* Descripción: Descripción del producto que muestra información sobre este.
* Foto: Enlace a un repositorio Online donde se almacenan las fotos de cada producto.
****

==== Usuarios.
Son los usuarios registrados en la página, ya sean administradores o usuarios normales.

****
* _id: Identificador único de cada usuario.
* Nombre: Nombre del usuario.
* Apellidos: Apellidos del usuario.
* Email: Correo electrónico del usuario.
* Dni: Dni del usuario registrado en la página.
* idSolid: Dirección para acceder al pod del usuario. (Por ejemplo: usuario.solidcommunity.net)
* Contraseña: Contraseña de acceso del usuario, que se guarda cifrada en la base de datos.
****